### ISSUE TITLE
where do you implement concatenation

### ISSUE THREAD

**Issue by bsun0802** [mateuszbuda/brain-segmentation-pytorch#10]
Hi, 

From the image of the architecture in README.md, it seems that a concatenation was implemented. But from your `unet.py`, I couldn't find where do concatenation was implemented? I have trouble implementing the concatenation in U-net, Could you please  help me understand it?

Great Thanks.

**Comment by mateuszbuda** [comment]
Hi, thank you for your interest in my code
Concatenation of feature maps is in forward function: https://github.com/mateuszbuda/brain-segmentation-pytorch/blob/8ef2e2d423b67b53ec8113fc71a9b968bb0f66e7/unet.py#L54

Let me know if you have any other questions.

Best regards,
Mat

**Comment by bsun0802** [comment]
Thanks!
